"""phase 04 rag memory and knowledge

Revision ID: 788bf6c7111d
Revises: 51d0cb4c3013
Create Date: 2026-08-31 15:34:28.306655
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "788bf6c7111d"
down_revision: str | None = "51d0cb4c3013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding_cache",
        sa.Column("normalized_sha256", sa.String(length=64), nullable=False),
        sa.Column("embedding_model", sa.String(length=64), nullable=False),
        sa.Column("embedding_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("normalized_sha256", "embedding_model"),
    )
    op.create_table(
        "student_memories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("statement_sha256", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.String(length=8), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("observed_count", sa.Integer(), nullable=False),
        sa.Column("derived_by", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["subject_id"], ["tutortwin_subjects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["superseded_by"], ["student_memories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_id", "statement_sha256", name="uq_memory_statement"),
    )
    op.create_index(
        "ix_memory_subject_active",
        "student_memories",
        ["subject_id", "kind", "superseded_by"],
        unique=False,
    )
    op.create_table(
        "topic_stats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("correct", sa.Integer(), nullable=False),
        sa.Column("hints_used", sa.Integer(), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["subject_id"], ["tutortwin_subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_id", "topic", name="uq_topic_stat"),
    )
    op.create_index("ix_topic_subject", "topic_stats", ["subject_id"], unique=False)
    op.create_table(
        "conversation_summaries",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("covered_message_count", sa.Integer(), nullable=False),
        sa.Column("persona_version", sa.Integer(), nullable=False),
        sa.Column("generated_by", sa.String(length=16), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("conversation_id"),
    )
    op.create_table(
        "knowledge_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("visibility", sa.String(length=24), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("tutor_id", sa.Uuid(), nullable=True),
        sa.Column("course_id", sa.String(length=64), nullable=True),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("chunker_version", sa.String(length=32), nullable=False),
        sa.Column("embedding_model", sa.String(length=64), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(visibility = 'STUDENT_PRIVATE' AND subject_id IS NOT NULL) OR (visibility = 'TUTOR' AND tutor_id IS NOT NULL) OR (visibility = 'COURSE' AND course_id IS NOT NULL) OR (visibility = 'CONVERSATION' AND conversation_id IS NOT NULL) OR visibility = 'GLOBAL_CURATED'",
            name="ck_source_visibility_owner",
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subject_id"], ["tutortwin_subjects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tutor_id"], ["tutors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "content_sha256",
            "visibility",
            "subject_id",
            "tutor_id",
            "parser_version",
            "chunker_version",
            "embedding_model",
            name="uq_source_content",
        ),
    )
    op.create_index(
        "ix_source_subject", "knowledge_sources", ["subject_id", "visibility"], unique=False
    )
    op.create_index(
        "ix_source_tutor", "knowledge_sources", ["tutor_id", "visibility"], unique=False
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("normalized_sha256", sa.String(length=64), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("section", sa.String(length=512), nullable=True),
        sa.Column("token_estimate", sa.Integer(), nullable=False),
        sa.Column("visibility", sa.String(length=24), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("tutor_id", sa.Uuid(), nullable=True),
        sa.Column("course_id", sa.String(length=64), nullable=True),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("embedding_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("embedding_model", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(visibility = 'STUDENT_PRIVATE' AND subject_id IS NOT NULL) OR (visibility = 'TUTOR' AND tutor_id IS NOT NULL) OR (visibility = 'COURSE' AND course_id IS NOT NULL) OR (visibility = 'CONVERSATION' AND conversation_id IS NOT NULL) OR visibility = 'GLOBAL_CURATED'",
            name="ck_chunk_visibility_owner",
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["knowledge_sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subject_id"], ["tutortwin_subjects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tutor_id"], ["tutors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "ordinal", name="uq_chunk_ordinal"),
    )
    op.create_index("ix_chunk_source", "document_chunks", ["source_id"], unique=False)
    op.create_index(
        "ix_chunk_visibility_subject", "document_chunks", ["visibility", "subject_id"], unique=False
    )
    op.create_index(
        "ix_chunk_visibility_tutor", "document_chunks", ["visibility", "tutor_id"], unique=False
    )
    op.create_table(
        "retrieval_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("request_event_id", sa.Uuid(), nullable=True),
        sa.Column("performed", sa.Boolean(), nullable=False),
        sa.Column("skip_reason", sa.String(length=48), nullable=True),
        sa.Column("top_k", sa.Integer(), nullable=False),
        sa.Column("returned", sa.Integer(), nullable=False),
        sa.Column("candidates_scanned", sa.Integer(), nullable=False),
        sa.Column("embedding_calls", sa.Integer(), nullable=False),
        sa.Column("query_ms", sa.Integer(), nullable=False),
        sa.Column("chunk_ids_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["request_event_id"], ["request_events.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["subject_id"], ["tutortwin_subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_retrieval_subject_created",
        "retrieval_events",
        ["subject_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Full-text index for the keyword half of hybrid retrieval. Without it the
    # ts_vector is recomputed per row on every search.
    op.execute(
        "CREATE INDEX ix_chunk_fulltext ON document_chunks USING GIN (to_tsvector('english', text))"
    )

    # Embedding aliases. Model IDs live in the catalog, never in business code.
    for provider, model_id, cost_in in (
        ("openai", "text-embedding-3-small", 20),
        ("openai", "text-embedding-3-large", 130),
    ):
        op.execute(
            sa.text(
                """
                INSERT INTO model_catalog (
                    id, model_alias, provider, model_id, is_active,
                    input_cost_micros_per_1k, output_cost_micros_per_1k, rate_version
                )
                VALUES (gen_random_uuid(), 'EMBEDDING', :provider, :model_id, :active,
                        :cost_in, 0, '2026-08')
                ON CONFLICT ON CONSTRAINT uq_model_catalog DO NOTHING
                """
            ).bindparams(
                provider=provider,
                model_id=model_id,
                active=(model_id == "text-embedding-3-small"),
                cost_in=cost_in,
            )
        )


def downgrade() -> None:
    op.execute("DELETE FROM model_catalog WHERE model_alias = 'EMBEDDING'")
    op.execute("DROP INDEX IF EXISTS ix_chunk_fulltext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_retrieval_subject_created", table_name="retrieval_events")
    op.drop_table("retrieval_events")
    op.drop_index("ix_chunk_visibility_tutor", table_name="document_chunks")
    op.drop_index("ix_chunk_visibility_subject", table_name="document_chunks")
    op.drop_index("ix_chunk_source", table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index("ix_source_tutor", table_name="knowledge_sources")
    op.drop_index("ix_source_subject", table_name="knowledge_sources")
    op.drop_table("knowledge_sources")
    op.drop_table("conversation_summaries")
    op.drop_index("ix_topic_subject", table_name="topic_stats")
    op.drop_table("topic_stats")
    op.drop_index("ix_memory_subject_active", table_name="student_memories")
    op.drop_table("student_memories")
    op.drop_table("embedding_cache")
    # ### end Alembic commands ###
