"""phase 06 admin control plane

Revision ID: a6e36c18df31
Revises: de2503b61a7d
Create Date: 2026-09-02 11:10:47.088817
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a6e36c18df31"
down_revision: str | None = "de2503b61a7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_login_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("successful", sa.Boolean(), nullable=False),
        sa.Column("failure_reason", sa.String(length=48), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_login_attempt_email_time", "admin_login_attempts", ["email", "created_at"], unique=False
    )
    op.create_index(
        "ix_login_attempt_ip_time",
        "admin_login_attempts",
        ["ip_address", "created_at"],
        unique=False,
    )
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("totp_secret_encrypted", sa.String(length=512), nullable=True),
        sa.Column("totp_enabled", sa.Boolean(), nullable=False),
        sa.Column("failed_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('SUPER_ADMIN', 'ADMIN', 'ACADEMIC_ADMIN', 'SUPPORT', 'TUTOR_VIEWER', 'USAGE_VIEWER')",
            name="ck_admin_role",
        ),
        sa.CheckConstraint("status IN ('ACTIVE', 'DISABLED')", name="ck_admin_status"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_admin_email"),
    )
    op.create_index("ix_admin_status", "admin_users", ["status"], unique=False)
    op.create_table(
        "admin_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admin_user_id", sa.Uuid(), nullable=False),
        sa.Column("token_sha256", sa.String(length=64), nullable=False),
        sa.Column("csrf_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(length=64), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(["admin_user_id"], ["admin_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_sha256", name="uq_session_token"),
    )
    op.create_index("ix_session_expiry", "admin_sessions", ["expires_at"], unique=False)
    op.create_index(
        "ix_session_user_active", "admin_sessions", ["admin_user_id", "revoked_at"], unique=False
    )
    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("block_key", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("body", sa.String(length=8000), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("author_admin_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('DRAFT', 'ACTIVE', 'RETIRED')", name="ck_prompt_status"),
        sa.ForeignKeyConstraint(["author_admin_id"], ["admin_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("block_key", "version", name="uq_prompt_block_version"),
    )
    op.create_index("ix_prompt_active", "prompt_versions", ["block_key", "status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_prompt_active", table_name="prompt_versions")
    op.drop_table("prompt_versions")
    op.drop_index("ix_session_user_active", table_name="admin_sessions")
    op.drop_index("ix_session_expiry", table_name="admin_sessions")
    op.drop_table("admin_sessions")
    op.drop_index("ix_admin_status", table_name="admin_users")
    op.drop_table("admin_users")
    op.drop_index("ix_login_attempt_ip_time", table_name="admin_login_attempts")
    op.drop_index("ix_login_attempt_email_time", table_name="admin_login_attempts")
    op.drop_table("admin_login_attempts")
    # ### end Alembic commands ###
