"""phase 05 learning engine

Revision ID: de2503b61a7d
Revises: 788bf6c7111d
Create Date: 2026-09-02 10:05:05.673740
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "de2503b61a7d"
down_revision: str | None = "788bf6c7111d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("artifact_format", sa.String(length=8), nullable=False),
        sa.Column("blob_key", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("generated_by", sa.String(length=16), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "generated_by IN ('deterministic', 'model_spec')", name="ck_artifact_generated_by"
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["subject_id"], ["tutortwin_subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_id", "sha256", name="uq_artifact_subject_sha"),
    )
    op.create_index(
        "ix_artifact_subject_created",
        "learning_artifacts",
        ["subject_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "study_notes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("topic", sa.String(length=200), nullable=False),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dropped_citations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["subject_id"], ["tutortwin_subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_notes_subject_topic", "study_notes", ["subject_id", "topic"], unique=False)
    op.create_table(
        "assessments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("topic", sa.String(length=120), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("total_marks", sa.Integer(), nullable=False),
        sa.Column("blueprint", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("truncated_reason", sa.String(length=200), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("artifact_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('QUIZ', 'MOCK_TEST', 'PRACTICE_SET')", name="ck_assessment_kind"
        ),
        sa.ForeignKeyConstraint(["artifact_id"], ["learning_artifacts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["knowledge_sources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["subject_id"], ["tutortwin_subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_assessment_subject_created", "assessments", ["subject_id", "created_at"], unique=False
    )
    op.create_table(
        "flashcard_decks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("topic", sa.String(length=120), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["knowledge_sources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["subject_id"], ["tutortwin_subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_id", "name", name="uq_deck_subject_name"),
    )
    op.create_table(
        "homework_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("problem_text", sa.Text(), nullable=False),
        sa.Column("topic", sa.String(length=120), nullable=True),
        sa.Column("stage", sa.String(length=24), nullable=False),
        sa.Column("shown_steps", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("hints_given", sa.Integer(), nullable=False),
        sa.Column("student_answer", sa.Text(), nullable=True),
        sa.Column("verification_verdict", sa.String(length=20), nullable=True),
        sa.Column("verification_method", sa.String(length=24), nullable=True),
        sa.Column("media_id", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["media_id"], ["media_objects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["subject_id"], ["tutortwin_subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_homework_conversation",
        "homework_tasks",
        ["conversation_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "assessment_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("awarded_marks", sa.Float(), nullable=True),
        sa.Column("total_marks", sa.Integer(), nullable=False),
        sa.Column("manual_review", sa.Boolean(), nullable=False),
        sa.Column("model_calls", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('ASSIGNED', 'IN_PROGRESS', 'SUBMITTED', 'GRADED')",
            name="ck_attempt_state",
        ),
        sa.ForeignKeyConstraint(["assessment_id"], ["assessments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subject_id"], ["tutortwin_subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_attempt_subject_state", "assessment_attempts", ["subject_id", "state"], unique=False
    )
    op.create_table(
        "assessment_questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("question_type", sa.String(length=24), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("marks", sa.Integer(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("answer_key", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint("marks >= 0", name="ck_question_marks"),
        sa.ForeignKeyConstraint(["assessment_id"], ["assessments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assessment_id", "number", name="uq_question_number"),
    )
    op.create_table(
        "flashcards",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deck_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("front", sa.Text(), nullable=False),
        sa.Column("back", sa.Text(), nullable=False),
        sa.Column("topic", sa.String(length=120), nullable=True),
        sa.Column("difficulty", sa.String(length=16), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_citation", sa.String(length=512), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("ease_factor", sa.Float(), nullable=False),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("due_on", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("ease_factor >= 1.3", name="ck_card_ease_floor"),
        sa.ForeignKeyConstraint(["deck_id"], ["flashcard_decks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subject_id"], ["tutortwin_subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deck_id", "content_sha256", name="uq_card_deck_content"),
    )
    op.create_index("ix_card_due", "flashcards", ["subject_id", "due_on"], unique=False)
    op.create_table(
        "attempt_responses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("selected_option", sa.Integer(), nullable=True),
        sa.Column("text_answer", sa.Text(), nullable=True),
        sa.Column("awarded_marks", sa.Float(), nullable=False),
        sa.Column("max_marks", sa.Integer(), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("evidence", sa.String(length=256), nullable=True),
        sa.Column("graded_by", sa.String(length=16), nullable=False),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "graded_by IN ('deterministic', 'model')",
            name="ck_response_graded_by",
        ),
        sa.ForeignKeyConstraint(["attempt_id"], ["assessment_attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_id"], ["assessment_questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id", "question_id", name="uq_response_attempt_question"),
    )
    op.create_table(
        "flashcard_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("grade", sa.String(length=8), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("ease_factor", sa.Float(), nullable=False),
        sa.Column("due_on", sa.Date(), nullable=False),
        sa.Column(
            "reviewed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["card_id"], ["flashcards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subject_id"], ["tutortwin_subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_review_card_time", "flashcard_reviews", ["card_id", "reviewed_at"], unique=False
    )
    # `ix_chunk_fulltext` is a functional GIN index created by raw SQL in Phase
    # 04, so autogenerate cannot see it in the model metadata and proposes
    # dropping it on every subsequent revision. Dropping it would silently
    # disable lexical retrieval, so the proposed drop is deleted here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_review_card_time", table_name="flashcard_reviews")
    op.drop_table("flashcard_reviews")
    op.drop_table("attempt_responses")
    op.drop_index("ix_card_due", table_name="flashcards")
    op.drop_table("flashcards")
    op.drop_table("assessment_questions")
    op.drop_index("ix_attempt_subject_state", table_name="assessment_attempts")
    op.drop_table("assessment_attempts")
    op.drop_index("ix_homework_conversation", table_name="homework_tasks")
    op.drop_table("homework_tasks")
    op.drop_table("flashcard_decks")
    op.drop_index("ix_assessment_subject_created", table_name="assessments")
    op.drop_table("assessments")
    op.drop_index("ix_notes_subject_topic", table_name="study_notes")
    op.drop_table("study_notes")
    op.drop_index("ix_artifact_subject_created", table_name="learning_artifacts")
    op.drop_table("learning_artifacts")
    # ### end Alembic commands ###
