"""phase_09_subscriptions_and_payments

Revision ID: f211de0a201a
Revises: c4a17be9d520
Create Date: 2026-09-07 15:13:08.042919
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f211de0a201a'
down_revision: str | None = 'c4a17be9d520'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_name', sa.String(length=200), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=32), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('tutor_name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['tutortwin_subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signup_status_created', 'signups', ['status', 'created_at'], unique=False)
    op.create_index('ix_signup_whatsapp', 'signups', ['whatsapp_number'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('signup_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.String(length=128), nullable=False),
    sa.Column('gateway', sa.String(length=32), nullable=False),
    sa.Column('gateway_payment_id', sa.String(length=128), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('plan_code', sa.String(length=64), nullable=False),
    sa.Column('plan_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('payment_session_id', sa.Text(), nullable=True),
    sa.Column('gateway_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signup_id'], ['signups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_payment_order')
    )
    op.create_index('ix_payment_signup', 'payments', ['signup_id'], unique=False)
    op.create_index('ix_payment_status', 'payments', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_status', table_name='payments')
    op.drop_index('ix_payment_signup', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_signup_whatsapp', table_name='signups')
    op.drop_index('ix_signup_status_created', table_name='signups')
    op.drop_table('signups')
    # ### end Alembic commands ###
